import type { Metadata } from "next";
import "./globals.css";
import Layout from "../components/Layout/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen bg-slate-100 flex-col md:flex-row md:overflow-hidden">
          <div className="w-full flex-none md:w-64">
            <Layout />
          </div>
          <div className="flex-grow pl-2 pt-2 overflow-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
